name: Deploy VSCode Extension

on:
  push:
    branches:
      - main  # Set this to the branch from which you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set this to your required node.js version

    - name: Install dependencies
      run: npm install

    - name: Package Extension
      run: npx vsce package

    - name: Publish Extension
      env:
        VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_PAT }}
      run: npx vsce publish
